name: Costco PM Alert

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes (UTC)

jobs:
  run-alert:
    runs-on: ubuntu-latest
    env:
      CI: "true"
      # Match your local run:
      BROWSER: "webkit"              # your script already defaults to webkit on CI, but explicit is fine
      HEADLESS: "true"               # prefer headless on CI; use xvfb if you really need false
      POST_STATUS_UPDATES: "true"
      BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
      BSKY_APP_PASSWORD: ${{ secrets.BSKY_APP_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # if you don’t have a requirements.txt, install directly:
          # pip install playwright python-dotenv atproto

      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps webkit

      # If you *must* run headful on CI, wrap with xvfb:
      # - name: Run script (headful)
      #   run: xvfb-run -a python costcopm_alert.py

      - name: Run script
        run: python costcopm_alert.py
