name: CostcoPM Alert

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes (example)

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      CI: true
      BROWSER: webkit
      HEADLESS: true
      # Set your Bluesky secrets in the repo settings
      BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
      BSKY_APP_PASSWORD: ${{ secrets.BSKY_APP_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt || true
          pip install playwright atproto python-dotenv

      - name: Install Playwright browsers
        uses: microsoft/playwright-github-action@v1
        with:
          with-deps: true

      - name: Run CostcoPM
        run: |
          mkdir -p artifacts
          python -V
          python costcopm_alert.py
        continue-on-error: true

      - name: List files for debugging
        if: always()
        run: |
          echo "== workspace =="
          ls -la
          echo "== artifacts =="
          ls -la artifacts || true
          echo "== grep for api-sample.json =="
          find . -name "api-sample.json" -maxdepth 2 -ls || true

      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: costcopm-debug
          path: |
            artifacts/**
            api-sample.json
            page.html
            costco.png
          if-no-files-found: warn
