name: Costco Precious Metals Alert

on:
  schedule:
    # Every 30 minutes
    - cron: "*/30 * * * *"
  workflow_dispatch:  # allow manual runs

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
      BSKY_APP_PASSWORD: ${{ secrets.BSKY_APP_PASSWORD }}
      CI: true
      BROWSER: chromium
      HEADLESS: true
      # Optional if you only want posts during the day:
      # POST_ONLY_DURING_DAY: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install playwright python-dotenv atproto
          playwright install --with-deps chromium

      - name: Run CostcoPM alert
        run: |
          echo "Running Costco Precious Metals Alert..."
          python costcopm_alert.py
