# .github/workflows/costcopm_alert.yml
name: Costco Precious Metals Alert

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
      BSKY_APP_PASSWORD: ${{ secrets.BSKY_APP_PASSWORD }}
      CI: "1"
      BROWSER: webkit          # <- use WebKit on CI
      HEADLESS: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install playwright python-dotenv atproto
          python -m playwright install --with-deps webkit   # <- install webkit

      - name: Run CostcoPM alert
        run: |
          echo "Running Costco Precious Metals Alert..."
          python costcopm_alert.py

      # Optional: collect artifacts for debugging
      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: costcopm-debug
          path: |
            costco.png
            page.html
            api-sample.json
