# .github/workflows/costcopm.yml
name: CostcoPM Bot

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (Playwright + browsers)
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium firefox

      - name: Run CostcoPM
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_APP_PASSWORD: ${{ secrets.BSKY_APP_PASSWORD }}
          BROWSER: chromium
          CI: "1"
        run: |
          python costcopm_alert.py
