# .github/workflows/costcopm.yml
name: CostcoPM Bot

on:
  schedule:
    - cron: "*/30 * * * *"  # every 30 min (UTC)
  workflow_dispatch: {}

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: costcopm-bot
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          # If not using a requirements.txt, explicitly:
          # pip install python-dotenv playwright atproto
          python -m playwright install --with-deps firefox

      - name: Run CostcoPM
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_APP_PASSWORD: ${{ secrets.BSKY_APP_PASSWORD }}
          # Optional: control posting window inside your script
          POST_ONLY_DURING_DAY: "true"
        run: |
          python costcopm_alert.py
