name: CostcoPM Alert

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes (UTC)

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      CI: "true"
      BROWSER: "webkit"
      HEADLESS: "true"
      # Ensure these match what your script reads:
      BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
      BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          # ensure these are present even if not pinned
          pip install playwright atproto python-dotenv

      # Install WebKit + required system libraries on Ubuntu
      - name: Install Playwright browsers & system deps (WebKit)
        run: |
          python -m playwright install --with-deps webkit

      - name: Run CostcoPM
        run: |
          mkdir -p artifacts
          python -V
          python costcopm_alert.py

      - name: List files for debugging
        if: always()
        run: |
          echo "== workspace =="
          ls -la
          echo "== artifacts =="
          ls -la artifacts || true
          echo "== grep for api-sample.json =="
          find . -maxdepth 3 -name "api-sample.json" -ls || true

      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: costcopm-debug
          path: |
            **/artifacts/**
            **/api-sample.json
            **/page.html
            **/costco.png
          if-no-files-found: warn
